### PR TITLE
Add indent_size to .editorconfig

### PR DESCRIPTION
**Pull request by stanislavshabalin**
... so the code would look nicer on Github

Before:

```
class PostcsssortingCommand(sublime_plugin.TextCommand):
        def run(self, edit):
                if not self.has_selection():
                        region = sublime.Region(0, self.view.size())
                        originalBuffer = self.view.substr(region)
                        processed = self.sorting(originalBuffer)
```

After:

```
class PostcsssortingCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        if not self.has_selection():
            region = sublime.Region(0, self.view.size())
            originalBuffer = self.view.substr(region)
            processed = self.sorting(originalBuffer)
```

### CODE REVIEW

**Comment by hudochenkov** [comment]
I think this is unnecessary. The beauty of tabs is that you can use whatever width you want for indentation in your editor and no one force you to use their preferences.

And `indent_size` is for spaces. For tabs there is `tab_width` http://editorconfig.org/

**Comment by hudochenkov** [comment]
Also there is Chrome/Opera extension for this fix https://github.com/sindresorhus/tab-size-on-github :) And it will not be affect developers who would use editorconfig in their editors with their preferred tabs width.

**Comment by stanislavshabalin** [comment]
Didn't realize there's a tradeoff with this, thanks for pointing that out!

Github's 8 characters default is not pretty though :-)
I'll check out the extension, too bad it's only for two browsers.

**Comment by stanislavshabalin** [comment]
> And indent_size is for spaces. For tabs there is tab_width http://editorconfig.org/

Don't know what they were having in mind, http://editorconfig.org:

> **tab_width** defaults to the value of **indent_size** and doesn't usually need to be specified.

**Comment by hudochenkov** [comment]
I think it meant that `indent_size` can be used as fallback for `tab_width` if `tab_width` is not in config, but `indent_size` is in. So your change was correct, but not exactly as it can be :)

**Pull request closed without merging**
