### PR TITLE
Add option for autosorting

### LINKED ISSUE #1: Auto-sorting on save
Is it possible to automatically sort CSS rules (on every file save, for example)?

### PR DESCRIPTION
**Pull request by stanislavshabalin**
Resolve #1

### CODE REVIEW

**Comment by hudochenkov** [comment]
Thank you @voxpuibr! My first received PR ever :)

**Comment by stanislavshabalin** [comment]
@hudochenkov and my first non-trivial PR as well :-)

P. S. That was mostly selfish, I would use this feature when it rolls out.

**Comment by hudochenkov** [comment]
I've posted new version 1.2.0. I believe it will be available in Package Control in about 10 minutes. You can check “Modified” at https://packagecontrol.io/packages/PostCSS%20Sorting if it updated. And you may need to restart Sublime Text because Package Control check updates only at loading, I think.

**Comment by stanislavshabalin** [comment]
Thank you!

**Pull request merged**
